export interface BlogPost {
  id: number;
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  readTime: string;
  date: string;
  image: string;
  featured: boolean;
  author: string;
  authorRole: string;
  content: BlogSection[];
  tags: string[];
}

export interface BlogSection {
  type: 'paragraph' | 'heading' | 'list' | 'quote' | 'highlight';
  text?: string;
  items?: string[];
}

export const blogPosts: BlogPost[] = [
  {
    id: 1,
    slug: 'what-is-vedic-astrology',
    title: "What is Vedic Astrology? A Complete Beginner's Guide",
    excerpt: 'Discover the ancient wisdom of Jyotish, the science of light that has guided millions for over 5,000 years.',
    category: 'Basics',
    readTime: '8 min read',
    date: 'Feb 1, 2026',
    image: '🌌',
    featured: true,
    author: 'Pandit Arjun Sharma',
    authorRole: 'Senior Vedic Astrologer',
    tags: ['Vedic Astrology', 'Jyotish', 'Beginners', 'Introduction'],
    content: [
      { type: 'paragraph', text: 'Vedic astrology, known as Jyotish in Sanskrit (meaning "science of light"), is one of the oldest and most complete systems of astrology in the world. Dating back over 5,000 years to the sacred Vedic scriptures of ancient India, it offers a profound framework for understanding the cosmic influences that shape our lives, personalities, and destinies.' },
      { type: 'heading', text: 'The Origins of Jyotish' },
      { type: 'paragraph', text: 'Jyotish is considered one of the six Vedangas (limbs of the Vedas), making it an integral part of India\'s spiritual heritage. The ancient sages known as Rishis observed the movements of celestial bodies and recognized their deep connection to human affairs. They encoded this knowledge in classical texts like Brihat Parashara Hora Shastra, which remains the foundational text of Vedic astrology to this day.' },
      { type: 'highlight', text: '"The stars incline, they do not compel. Jyotish illuminates the path — you choose how to walk it."' },
      { type: 'heading', text: 'How is Vedic Astrology Different from Western Astrology?' },
      { type: 'list', items: [
        'Uses the Sidereal zodiac (based on fixed star positions) vs. Tropical zodiac used in Western astrology',
        'Places strong emphasis on the Moon sign (Rashi) and Ascendant (Lagna) over the Sun sign',
        'Incorporates the 27 Nakshatras (lunar mansions), a uniquely Vedic system',
        'Uses the Dasha system — planetary periods that show life\'s unfolding chapters',
        'Focuses on karma, dharma, and spiritual evolution',
        'Employs divisional charts (Varga charts) for deeper analysis of specific life areas',
      ]},
      { type: 'heading', text: 'The Three Pillars of Vedic Astrology' },
      { type: 'paragraph', text: 'Vedic astrology rests on three interconnected pillars: the birth chart (Kundli or Janma Kundali), planetary periods (Dashas), and transits (Gocharas). Together, these tools allow an astrologer to map out the karmic blueprint of a soul and predict major life events with remarkable accuracy.' },
      { type: 'heading', text: 'What Can Vedic Astrology Reveal?' },
      { type: 'list', items: [
        'Career and professional inclinations',
        'Relationship compatibility and marriage timing',
        'Health tendencies and vulnerabilities',
        'Financial prospects and wealth periods',
        'Spiritual path and life purpose',
        'Auspicious timing for major decisions (Muhurta)',
      ]},
      { type: 'paragraph', text: 'Whether you are seeking clarity about your relationships, career, health, or spiritual path, Vedic astrology offers a remarkably precise and compassionate lens through which to view your life\'s unfolding journey.' },
    ],
  },
  {
    id: 2,
    slug: 'planetary-guide',
    title: 'The Nine Planets (Navagraha) in Vedic Astrology',
    excerpt: 'Learn about the cosmic influences of the Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn, Rahu, and Ketu.',
    category: 'Planets',
    readTime: '12 min read',
    date: 'Jan 28, 2026',
    image: '🪐',
    featured: true,
    author: 'Dr. Meera Krishnan',
    authorRole: 'Jyotish Acharya',
    tags: ['Navagraha', 'Planets', 'Vedic', 'Cosmic Influences'],
    content: [
      { type: 'paragraph', text: 'In Vedic astrology, nine celestial bodies — the Navagraha — are considered the primary cosmic influencers of human life. Unlike Western astrology\'s use of outer planets like Neptune and Pluto, Vedic astrology focuses on seven visible planets plus two shadow planets, Rahu and Ketu, the lunar nodes.' },
      { type: 'heading', text: '☉ Sun (Surya) — The Royal Planet' },
      { type: 'paragraph', text: 'The Sun represents the soul (Atma), ego, authority, father, and vitality. A strong Sun in the chart bestows leadership qualities, confidence, and success in government or administrative roles. It rules the sign of Leo and the 5th house.' },
      { type: 'heading', text: '☽ Moon (Chandra) — The Mind\'s Mirror' },
      { type: 'paragraph', text: 'The Moon governs the mind (Manas), emotions, mother, and intuition. In Vedic astrology, the Moon sign is considered more significant than the Sun sign, as it reflects our mental and emotional nature. It rules Cancer and is exalted in Taurus.' },
      { type: 'highlight', text: 'The Moon\'s Nakshatra placement at birth (Janma Nakshatra) is the foundation of the Dasha system — the planetary period timeline of your life.' },
      { type: 'heading', text: '♂ Mars (Mangal) — The Warrior' },
      { type: 'paragraph', text: 'Mars signifies energy, courage, siblings, and ambition. It drives action and determination. A well-placed Mars gives athletic ability, engineering talent, and military prowess. It rules Aries and Scorpio.' },
      { type: 'heading', text: '☿ Mercury (Budha) — The Intellectual' },
      { type: 'paragraph', text: 'Mercury governs intelligence, communication, trade, and analytical ability. Strong Mercury natives excel in writing, mathematics, business, and technology. It rules Gemini and Virgo.' },
      { type: 'heading', text: '♃ Jupiter (Guru) — The Great Benefic' },
      { type: 'paragraph', text: 'Jupiter is the most auspicious planet, representing wisdom, fortune, children, spirituality, and expansion. It is called the Guru (teacher) and its blessings bring abundance and higher knowledge. It rules Sagittarius and Pisces.' },
      { type: 'heading', text: '♀ Venus (Shukra) — The Planet of Love' },
      { type: 'paragraph', text: 'Venus rules love, beauty, marriage, arts, luxury, and sensual pleasures. A strong Venus brings charm, aesthetic sensibility, and harmonious relationships. It rules Taurus and Libra.' },
      { type: 'heading', text: '♄ Saturn (Shani) — The Karmic Teacher' },
      { type: 'paragraph', text: 'Saturn is the planet of karma, discipline, longevity, delays, and hard work. Though feared, a well-positioned Saturn creates tremendous patience, resilience, and ultimate success. It rules Capricorn and Aquarius.' },
      { type: 'heading', text: '☊ Rahu — The North Node' },
      { type: 'paragraph', text: 'Rahu is a shadow planet — the north lunar node — representing worldly desires, illusion, foreign lands, and obsession. It amplifies whatever it touches and can bring sudden rise to fame and material success.' },
      { type: 'heading', text: '☋ Ketu — The South Node' },
      { type: 'paragraph', text: 'Ketu, the south lunar node, represents spirituality, liberation, past-life karma, and detachment. It brings mystical experiences and can indicate areas where we have deep past-life expertise.' },
      { type: 'list', items: [
        'Sun rules: Soul, Authority, Father, Government',
        'Moon rules: Mind, Emotions, Mother, Intuition',
        'Mars rules: Energy, Courage, Siblings, Ambition',
        'Mercury rules: Intelligence, Communication, Trade',
        'Jupiter rules: Wisdom, Fortune, Children, Spirituality',
        'Venus rules: Love, Beauty, Marriage, Arts',
        'Saturn rules: Karma, Discipline, Longevity, Delays',
        'Rahu rules: Desires, Illusion, Foreign elements',
        'Ketu rules: Spirituality, Liberation, Past karma',
      ]},
    ],
  },
  {
    id: 3,
    slug: 'zodiac-signs',
    title: 'The 12 Rashi: Understanding Vedic Zodiac Signs',
    excerpt: 'Explore the unique characteristics, elements, and ruling planets of each zodiac sign in Vedic astrology.',
    category: 'Zodiac',
    readTime: '10 min read',
    date: 'Jan 25, 2026',
    image: '♈',
    featured: false,
    author: 'Pandit Arjun Sharma',
    authorRole: 'Senior Vedic Astrologer',
    tags: ['Rashi', 'Zodiac Signs', 'Elements', 'Vedic'],
    content: [
      { type: 'paragraph', text: 'In Vedic astrology, the 12 zodiac signs — called Rashi — form the backdrop against which the cosmic drama of the planets unfolds. Each Rashi is associated with a specific element, quality, ruling planet, and set of characteristics that color the expression of any planet placed within it.' },
      { type: 'highlight', text: 'Unlike Western astrology, your Vedic Sun sign may differ from what you\'re used to, because Jyotish uses the Sidereal zodiac aligned with actual star positions.' },
      { type: 'heading', text: 'The Fire Signs (Agni Tattva)' },
      { type: 'list', items: [
        'Aries (Mesha) ♈ — Ruled by Mars. Bold, pioneering, courageous, and impulsive. The warrior archetype.',
        'Leo (Simha) ♌ — Ruled by Sun. Regal, creative, generous, and leadership-oriented. The royal archetype.',
        'Sagittarius (Dhanu) ♐ — Ruled by Jupiter. Philosophical, adventurous, optimistic, and truth-seeking.',
      ]},
      { type: 'heading', text: 'The Earth Signs (Prithvi Tattva)' },
      { type: 'list', items: [
        'Taurus (Vrishabha) ♉ — Ruled by Venus. Stable, sensual, patient, and materialistically oriented.',
        'Virgo (Kanya) ♍ — Ruled by Mercury. Analytical, meticulous, health-conscious, and service-oriented.',
        'Capricorn (Makara) ♑ — Ruled by Saturn. Disciplined, ambitious, practical, and career-focused.',
      ]},
      { type: 'heading', text: 'The Air Signs (Vayu Tattva)' },
      { type: 'list', items: [
        'Gemini (Mithuna) ♊ — Ruled by Mercury. Curious, communicative, versatile, and intellectually restless.',
        'Libra (Tula) ♎ — Ruled by Venus. Diplomatic, aesthetic, relationship-focused, and justice-seeking.',
        'Aquarius (Kumbha) ♒ — Ruled by Saturn. Humanitarian, unconventional, idealistic, and community-minded.',
      ]},
      { type: 'heading', text: 'The Water Signs (Jala Tattva)' },
      { type: 'list', items: [
        'Cancer (Karka) ♋ — Ruled by Moon. Nurturing, intuitive, family-oriented, and emotionally deep.',
        'Scorpio (Vrishchika) ♏ — Ruled by Mars. Intense, transformative, mysterious, and psychically gifted.',
        'Pisces (Meena) ♓ — Ruled by Jupiter. Compassionate, imaginative, spiritual, and boundlessly empathetic.',
      ]},
      { type: 'paragraph', text: 'Understanding your Rashi — particularly your Moon sign (Chandra Rashi) and Ascendant (Lagna Rashi) — provides the most accurate portrait of your personality, emotional world, and life path in Vedic astrology.' },
    ],
  },
  {
    id: 4,
    slug: 'birth-chart-houses',
    title: 'The 12 Houses of the Birth Chart Explained',
    excerpt: 'Each house in your Kundli represents different areas of life. Learn what they reveal about your destiny.',
    category: 'Houses',
    readTime: '15 min read',
    date: 'Jan 20, 2026',
    image: '🏠',
    featured: false,
    author: 'Dr. Meera Krishnan',
    authorRole: 'Jyotish Acharya',
    tags: ['Houses', 'Kundli', 'Birth Chart', 'Bhavas'],
    content: [
      { type: 'paragraph', text: 'The birth chart (Kundli or Janam Kundali) is divided into 12 sections called Bhavas (houses). Each Bhava governs a specific area of life — from personality and wealth to relationships and spirituality. Understanding the houses is fundamental to reading any Vedic birth chart.' },
      { type: 'heading', text: 'The Personal Houses (1-3)' },
      { type: 'list', items: [
        '1st House (Lagna/Ascendant): Self, personality, physical body, overall life direction. The most important house.',
        '2nd House (Dhana): Wealth, family, speech, food, early education, and accumulated resources.',
        '3rd House (Sahaja): Courage, siblings, communication, short journeys, and hands/arms.',
      ]},
      { type: 'heading', text: 'The Security Houses (4-6)' },
      { type: 'list', items: [
        '4th House (Sukha): Home, mother, emotional happiness, vehicles, real estate, and inner peace.',
        '5th House (Putra): Children, creativity, romance, speculation, past-life merit, and intelligence.',
        '6th House (Ari): Enemies, debts, disease, daily work, service, legal disputes, and competition.',
      ]},
      { type: 'highlight', text: 'The 1st, 5th, and 9th houses form the Dharma Trikona — the triangle of soul purpose and spiritual merit.' },
      { type: 'heading', text: 'The Relationship Houses (7-9)' },
      { type: 'list', items: [
        '7th House (Kalatra): Marriage, partnerships, business associates, and open enemies.',
        '8th House (Randhra): Transformation, hidden wealth, longevity, occult, inheritance, and sudden changes.',
        '9th House (Dharma): Father, fortune, higher education, spirituality, long journeys, and guru.',
      ]},
      { type: 'heading', text: 'The Public Houses (10-12)' },
      { type: 'list', items: [
        '10th House (Karma): Career, public reputation, authority, government, and life achievement.',
        '11th House (Labha): Gains, income, social networks, elder siblings, and fulfillment of desires.',
        '12th House (Vyaya): Loss, expenses, foreign lands, moksha (liberation), hospitals, and hidden matters.',
      ]},
      { type: 'paragraph', text: 'The interplay between the houses, their lords (ruling planets), and the planets placed within them creates the rich tapestry of your Kundli reading. A skilled Vedic astrologer synthesizes all these elements to reveal your life\'s unique cosmic blueprint.' },
    ],
  },
  {
    id: 5,
    slug: 'nakshatra-guide',
    title: 'Understanding the 27 Nakshatras (Lunar Mansions)',
    excerpt: "The Moon's position in a Nakshatra at birth reveals deep personality traits and life patterns.",
    category: 'Nakshatras',
    readTime: '20 min read',
    date: 'Jan 15, 2026',
    image: '🌙',
    featured: false,
    author: 'Pandit Arjun Sharma',
    authorRole: 'Senior Vedic Astrologer',
    tags: ['Nakshatras', 'Lunar Mansions', 'Moon', 'Janma Nakshatra'],
    content: [
      { type: 'paragraph', text: 'The 27 Nakshatras (lunar mansions) are one of the most unique and powerful tools in Vedic astrology. The zodiac is divided into 27 equal segments of 13°20\' each, and the Moon traverses all 27 in approximately one month. Your birth Nakshatra — determined by the Moon\'s position at the time of your birth — is called your Janma Nakshatra and forms the foundation of your entire Dasha system.' },
      { type: 'highlight', text: 'The Nakshatras pre-date even the Rashi (zodiac sign) system, making them the oldest and most refined layer of Vedic astrological analysis.' },
      { type: 'heading', text: 'The Four Goals (Purusharthas) of Nakshatras' },
      { type: 'paragraph', text: 'Each Nakshatra is associated with one of four goals: Dharma (purpose), Artha (material gain), Kama (desire), and Moksha (liberation). This reveals your soul\'s primary motivation in this lifetime.' },
      { type: 'heading', text: 'Notable Nakshatras and Their Characteristics' },
      { type: 'list', items: [
        'Ashwini (Aries 0°-13°20\') — Ruled by Ketu. Swift healers, adventurous pioneers, youthful energy.',
        'Rohini (Taurus 10°-23°20\') — Ruled by Moon. Creative, sensual, fertile, beloved by nature.',
        'Ardra (Gemini 6°40\'-20°) — Ruled by Rahu. Storms of transformation, intense intellect, empathy through suffering.',
        'Pushya (Cancer 3°20\'-16°40\') — Ruled by Saturn. The most auspicious Nakshatra, nourishing, spiritual.',
        'Magha (Leo 0°-13°20\') — Ruled by Ketu. Royal ancestry, leadership, reverence for tradition.',
        'Chitra (Virgo/Libra 23°20\'-6°40\') — Ruled by Mars. Artistic brilliance, architecture, beauty.',
        'Jyeshtha (Scorpio 16°40\'-30°) — Ruled by Mercury. Elder wisdom, protective, intense authority.',
        'Mula (Sagittarius 0°-13°20\') — Ruled by Ketu. Root-seeking, philosophical destruction leading to truth.',
        'Shravana (Capricorn 10°-23°20\') — Ruled by Moon. Listening, learning, teaching, divine connection.',
        'Revati (Pisces 16°40\'-30°) — Ruled by Mercury. Final Nakshatra: completion, compassion, journeys end.',
      ]},
      { type: 'heading', text: 'The Dasha System and Your Nakshatra' },
      { type: 'paragraph', text: 'Your Janma Nakshatra determines which planetary period (Dasha) you are born into. The Vimshottari Dasha system assigns each Nakshatra lord a specific number of years: Ketu (7), Venus (20), Sun (6), Moon (10), Mars (7), Rahu (18), Jupiter (16), Saturn (19), Mercury (17) — totaling 120 years, the full human lifespan in Vedic tradition.' },
    ],
  },
  {
    id: 6,
    slug: 'remedies-gemstones',
    title: 'Astrological Remedies: Gemstones, Mantras & Rituals',
    excerpt: 'Discover traditional remedies to strengthen beneficial planets and mitigate challenging influences.',
    category: 'Remedies',
    readTime: '14 min read',
    date: 'Jan 10, 2026',
    image: '💎',
    featured: false,
    author: 'Dr. Meera Krishnan',
    authorRole: 'Jyotish Acharya',
    tags: ['Remedies', 'Gemstones', 'Mantras', 'Upayas'],
    content: [
      { type: 'paragraph', text: 'Vedic astrology is not merely a predictive science — it is also deeply prescriptive. Through a system of remedial measures called Upayas, practitioners can work to strengthen beneficial planetary energies and reduce the impact of challenging cosmic influences. These remedies are deeply rooted in the understanding that we are not passive recipients of fate, but co-creators of our destiny.' },
      { type: 'heading', text: 'Gemstone Therapy (Ratna Chikitsa)' },
      { type: 'paragraph', text: 'Gemstones carry the vibrational frequency of their ruling planets. When worn correctly, they act as amplifiers, channeling beneficial planetary energy directly to the wearer. Only gems for benefic planets in your chart should be worn without consulting a qualified astrologer.' },
      { type: 'list', items: [
        'Ruby (Manik) — Strengthens the Sun. Enhances leadership, confidence, and vitality.',
        'Pearl (Moti) — Strengthens the Moon. Calms emotions, improves mental clarity, and enhances intuition.',
        'Red Coral (Moonga) — Strengthens Mars. Boosts courage, energy, and removes obstacles.',
        'Emerald (Panna) — Strengthens Mercury. Sharpens intellect, improves communication, and aids business.',
        'Yellow Sapphire (Pukhraj) — Strengthens Jupiter. Attracts wisdom, prosperity, and good fortune.',
        'Diamond (Heera) or White Sapphire — Strengthens Venus. Enhances love, beauty, and artistic talents.',
        'Blue Sapphire (Neelam) — Strengthens Saturn. The most powerful gem — must be tested carefully.',
        'Hessonite Garnet (Gomed) — Strengthens Rahu. Removes confusion and amplifies material success.',
        'Cat\'s Eye (Lehsunia) — Strengthens Ketu. Aids spiritual growth and protects from hidden enemies.',
      ]},
      { type: 'highlight', text: 'Warning: Always consult a qualified Vedic astrologer before wearing gemstones. A gem for a malefic planet can intensify challenges rather than resolve them.' },
      { type: 'heading', text: 'Mantra Therapy (Japa)' },
      { type: 'paragraph', text: 'Mantras are sacred sound vibrations that resonate with specific planetary energies. Regular recitation of a planet\'s beej (seed) mantra on its corresponding day and hour is one of the most potent and accessible remedies available.' },
      { type: 'list', items: [
        'Sun Mantra: "Om Hraam Hreem Hraum Sah Suryaya Namah" — 7,000 repetitions',
        'Moon Mantra: "Om Shraam Shreem Shraum Sah Chandraaya Namah" — 11,000 repetitions',
        'Mars Mantra: "Om Kraam Kreem Kraum Sah Bhaumaaya Namah" — 10,000 repetitions',
        'Mercury Mantra: "Om Braam Breem Braum Sah Budhaaya Namah" — 17,000 repetitions',
        'Jupiter Mantra: "Om Graam Greem Graum Sah Guruve Namah" — 19,000 repetitions',
        'Venus Mantra: "Om Draam Dreem Draum Sah Shukraaya Namah" — 16,000 repetitions',
        'Saturn Mantra: "Om Praam Preem Praum Sah Shanaishcharaaya Namah" — 23,000 repetitions',
      ]},
      { type: 'heading', text: 'Charity and Service (Daana)' },
      { type: 'paragraph', text: 'Each planet is associated with specific items whose donation (Daana) on the planet\'s day can reduce its challenging effects. Saturn\'s challenges are mitigated by serving the elderly and disabled. Sun\'s difficulties reduce with donations of wheat, jaggery, or copper on Sundays. Such acts of selfless service align us with the dharmic flow of the cosmos.' },
    ],
  },
  {
    id: 7,
    slug: 'dasha-system',
    title: 'The Vimshottari Dasha System: Your Life\'s Planetary Timeline',
    excerpt: 'Understand how the 120-year planetary period system maps out the major chapters and turning points of your life.',
    category: 'Advanced',
    readTime: '16 min read',
    date: 'Feb 5, 2026',
    image: '⏳',
    featured: false,
    author: 'Dr. Meera Krishnan',
    authorRole: 'Jyotish Acharya',
    tags: ['Dasha', 'Vimshottari', 'Planetary Periods', 'Timing'],
    content: [
      { type: 'paragraph', text: 'The Vimshottari Dasha system is perhaps the most brilliant and precise timing mechanism in all of astrology. Unlike transits, which affect everyone globally, Dashas are entirely personal — they unfold based on your specific Moon Nakshatra at birth and reveal the major themes and events that will dominate each chapter of your life.' },
      { type: 'highlight', text: 'Vimshottari means "120" in Sanskrit. The system spans 120 years — the ideal human lifespan — divided among the nine planets in a specific sequence.' },
      { type: 'heading', text: 'The Dasha Sequence and Durations' },
      { type: 'list', items: [
        'Ketu Dasha — 7 years: Spiritual experiences, isolation, karmic completion',
        'Venus Dasha — 20 years: Relationships, luxury, arts, material enjoyment',
        'Sun Dasha — 6 years: Career growth, authority, identity clarification',
        'Moon Dasha — 10 years: Emotional development, mother\'s influence, domestic life',
        'Mars Dasha — 7 years: Action, ambition, property, siblings',
        'Rahu Dasha — 18 years: Worldly ambition, foreign connections, rapid transformation',
        'Jupiter Dasha — 16 years: Wisdom, children, spiritual growth, expansion',
        'Saturn Dasha — 19 years: Hard work, karmic lessons, delays rewarded with permanence',
        'Mercury Dasha — 17 years: Intellect, business, communication, education',
      ]},
      { type: 'heading', text: 'Antardasha: The Sub-Periods' },
      { type: 'paragraph', text: 'Each main Dasha (Mahadasha) is subdivided into nine sub-periods called Antardashas. Each Antardasha is ruled by a different planet and brings that planet\'s themes into the foreground within the broader context of the Mahadasha. Further subdivisions — Pratyantardasha, Sookshma, and Prana — allow for increasingly precise timing of specific events.' },
    ],
  },
  {
    id: 8,
    slug: 'kundli-matching',
    title: 'Kundli Matching: The Complete Guide to Vedic Compatibility',
    excerpt: 'Learn the 8 Ashtakoota factors used to assess relationship compatibility before marriage in the Vedic tradition.',
    category: 'Compatibility',
    readTime: '18 min read',
    date: 'Feb 8, 2026',
    image: '💑',
    featured: false,
    author: 'Pandit Arjun Sharma',
    authorRole: 'Senior Vedic Astrologer',
    tags: ['Kundli Matching', 'Compatibility', 'Marriage', 'Ashtakoota'],
    content: [
      { type: 'paragraph', text: 'Kundli Milan (Kundli matching or Horoscope matching) is the traditional Vedic method for assessing the compatibility of two individuals before marriage. The system, known as Ashtakoota or Guna Milan, evaluates eight specific compatibility factors (Kootas) between two birth charts, assigning a total score out of 36 points.' },
      { type: 'highlight', text: 'A score of 18 or above out of 36 is generally considered acceptable. A score of 24+ suggests very good compatibility, while 30+ is considered exceptional.' },
      { type: 'heading', text: 'The 8 Ashtakoota Factors' },
      { type: 'list', items: [
        'Varna (1 point): Spiritual compatibility and ego development level',
        'Vashya (2 points): The degree of mutual attraction and magnetic pull',
        'Tara (3 points): Cosmic health, longevity, and well-being in the relationship',
        'Yoni (4 points): Sexual compatibility and intimate harmony',
        'Graha Maitri (5 points): Intellectual and psychological compatibility',
        'Gana (6 points): Temperament match: Deva (divine), Manushya (human), Rakshasa (demonic)',
        'Bhakoot (7 points): Emotional compatibility, wealth, and family harmony',
        'Nadi (8 points): Genetic and health compatibility — the most critical factor',
      ]},
      { type: 'heading', text: 'Beyond Guna Milan: A Complete Assessment' },
      { type: 'paragraph', text: 'While the Ashtakoota score provides a useful snapshot, experienced Vedic astrologers go much deeper. They examine the 7th house (marriage house) and its lord in both charts, the position of Venus and Jupiter, the Navamsa (D9) chart which reveals the deeper soul-level relationship, and Mangal Dosha — the Mars affliction affecting marriage.' },
    ],
  },
  {
    id: 9,
    slug: 'saturn-return',
    title: 'Saturn Return in Vedic Astrology: Life\'s Great Turning Points',
    excerpt: 'Every 29.5 years, Saturn returns to its natal position — triggering profound restructuring of your life path.',
    category: 'Planets',
    readTime: '11 min read',
    date: 'Feb 12, 2026',
    image: '🪐',
    featured: false,
    author: 'Dr. Meera Krishnan',
    authorRole: 'Jyotish Acharya',
    tags: ['Saturn', 'Shani', 'Sade Sati', 'Transits'],
    content: [
      { type: 'paragraph', text: 'In Vedic astrology, Saturn (Shani) is the karmic taskmaster who demands accountability. Every 29.5 years, Saturn completes its orbital cycle and returns to the exact zodiac position it occupied at your birth — an event known as Saturn Return, or in Vedic terms, the intensification of Shani\'s influence through Sade Sati or Kantaka Shani.' },
      { type: 'highlight', text: 'Sade Sati — the 7.5-year period when Saturn transits through the sign before, the sign of, and the sign after your natal Moon — is Saturn\'s most profound influence period.' },
      { type: 'heading', text: 'The Three Phases of Sade Sati' },
      { type: 'list', items: [
        'Rising Phase (2.5 years): Saturn enters the sign before your Moon sign. Challenges in health, finances, and relationships begin subtly.',
        'Peak Phase (2.5 years): Saturn conjuncts your natal Moon. Maximum pressure, transformation, and karmic reckoning.',
        'Setting Phase (2.5 years): Saturn moves to the sign after your Moon. Gradual relief as lessons are integrated.',
      ]},
      { type: 'paragraph', text: 'The first Saturn Return (around age 29-30) is when the carefree possibilities of youth solidify into real commitments. Career choices must crystallize. Relationships face tests of maturity. The second Saturn Return (around age 58-60) brings a reckoning of one\'s legacy and a powerful urge toward wisdom-sharing.' },
    ],
  },
  {
    id: 10,
    slug: 'muhurta-auspicious-timing',
    title: 'Muhurta: The Art of Choosing Auspicious Timing',
    excerpt: 'Learn how Vedic astrologers select the perfect cosmic moment for weddings, business launches, and life milestones.',
    category: 'Advanced',
    readTime: '13 min read',
    date: 'Feb 15, 2026',
    image: '⌚',
    featured: false,
    author: 'Pandit Arjun Sharma',
    authorRole: 'Senior Vedic Astrologer',
    tags: ['Muhurta', 'Auspicious Timing', 'Electional Astrology', 'Panchang'],
    content: [
      { type: 'paragraph', text: 'Muhurta, one of the six limbs of Vedic astrology, is the art of electional astrology — choosing the most auspicious cosmic moment to begin an important action. Just as we plant seeds at the optimal season for the best harvest, Muhurta teaches us to initiate major life events when the celestial energy is most supportive.' },
      { type: 'heading', text: 'The Five Limbs of Panchang' },
      { type: 'list', items: [
        'Tithi: The lunar day (30 in a lunar month). Certain Tithis are auspicious for beginnings; others for completion.',
        'Vara: The day of the week, each ruled by a planet (Sunday=Sun, Monday=Moon, etc.).',
        'Nakshatra: The Moon\'s Nakshatra on the chosen day — the most critical factor.',
        'Yoga: A calculated combination of Sun + Moon longitudes indicating the day\'s overall quality.',
        'Karana: Half of a Tithi, used for shorter time-frame electional analysis.',
      ]},
      { type: 'highlight', text: 'The best Muhurtas are found when the Lagna (Ascendant at the chosen time), the relevant house, and the Moon are all strong and free from malefic aspects.' },
      { type: 'heading', text: 'Common Uses of Muhurta' },
      { type: 'list', items: [
        'Vivaha Muhurta: Wedding ceremonies — the most commonly sought Muhurta',
        'Griha Pravesh: House-warming and moving into a new home',
        'Vyapara Arambha: Starting a new business or signing contracts',
        'Vidyarambha: Beginning formal education or learning a new skill',
        'Naamakaran: Naming ceremony for a newborn child',
        'Yatra: Beginning of a long journey',
      ]},
    ],
  },
  {
    id: 11,
    slug: 'jupiter-transit-2026',
    title: 'Jupiter Transit 2026: What It Means for Each Sign',
    excerpt: 'As Jupiter moves through Gemini in 2026, discover the expansive blessings and opportunities awaiting each zodiac sign.',
    category: 'Transits',
    readTime: '9 min read',
    date: 'Feb 18, 2026',
    image: '✨',
    featured: false,
    author: 'Dr. Meera Krishnan',
    authorRole: 'Jyotish Acharya',
    tags: ['Jupiter Transit', 'Guru Gochar', '2026', 'Predictions'],
    content: [
      { type: 'paragraph', text: 'Jupiter (Guru) is the most benefic planet in Vedic astrology, and its year-long transit through each sign is one of the most significant astrological events. In 2026, Jupiter continues its journey and brings its blessings of expansion, wisdom, and fortune to different areas of life for each sign.' },
      { type: 'highlight', text: 'Jupiter\'s transit is particularly auspicious when it aspects the 5th, 9th, or 11th house from your Moon sign — known as the Guru Purnima effect.' },
      { type: 'heading', text: 'Jupiter\'s Blessings by Sign' },
      { type: 'list', items: [
        'Aries (Mesha): Jupiter in the 3rd house — enhanced courage, short travel, sibling harmony',
        'Taurus (Vrishabha): Jupiter in the 2nd house — financial gains, family growth, eloquent speech',
        'Gemini (Mithuna): Jupiter in the 1st house — personal growth, health improvement, new beginnings',
        'Cancer (Karka): Jupiter in the 12th house — spiritual retreat, foreign connections, moksha significations',
        'Leo (Simha): Jupiter in the 11th house — exceptional gains, social expansion, wish fulfillment',
        'Virgo (Kanya): Jupiter in the 10th house — career advancement, recognition, authority roles',
        'Libra (Tula): Jupiter in the 9th house — spiritual growth, father\'s blessings, higher education',
        'Scorpio (Vrishchika): Jupiter in the 8th house — occult knowledge, inheritance, transformation',
        'Sagittarius (Dhanu): Jupiter in the 7th house — marriage, partnerships, business collaborations',
        'Capricorn (Makara): Jupiter in the 6th house — health improvement, overcoming enemies, service',
        'Aquarius (Kumbha): Jupiter in the 5th house — children, creativity, romantic joy, intelligence',
        'Pisces (Meena): Jupiter in the 4th house — home happiness, property, mother\'s health, vehicles',
      ]},
    ],
  },
  {
    id: 12,
    slug: 'mangal-dosha',
    title: 'Mangal Dosha: Understanding Mars\' Influence on Marriage',
    excerpt: 'Demystify one of Vedic astrology\'s most discussed concepts and learn if Mangal Dosha truly affects your marriage.',
    category: 'Compatibility',
    readTime: '10 min read',
    date: 'Feb 10, 2026',
    image: '❤️‍🔥',
    featured: false,
    author: 'Pandit Arjun Sharma',
    authorRole: 'Senior Vedic Astrologer',
    tags: ['Mangal Dosha', 'Mars', 'Marriage', 'Compatibility'],
    content: [
      { type: 'paragraph', text: 'Mangal Dosha (also called Kuja Dosha or Chovva Dosham) is one of the most widely known and often misunderstood concepts in Vedic astrology. It occurs when Mars (Mangal) is placed in the 1st, 2nd, 4th, 7th, 8th, or 12th house from the Lagna (Ascendant), Moon, or Venus in a birth chart.' },
      { type: 'highlight', text: 'It is estimated that approximately 40-50% of all people have some form of Mangal Dosha in their chart — making it far more common and manageable than popular fears suggest.' },
      { type: 'heading', text: 'Cancellations of Mangal Dosha' },
      { type: 'paragraph', text: 'Vedic texts identify numerous conditions that cancel or neutralize the effects of Mangal Dosha, making the concept far more nuanced than a simple yes/no diagnosis:' },
      { type: 'list', items: [
        'If both partners have Mangal Dosha (Double Dosha cancellation)',
        'If Mars is in its own sign (Aries or Scorpio) or exaltation sign (Capricorn)',
        'If Jupiter aspects Mars or the afflicted house',
        'If Mars is conjunct or aspected by benefic planets',
        'If the person is born on a Tuesday (ruled by Mars)',
        'After age 28, some texts hold that Mangal Dosha\'s intensity significantly reduces',
      ]},
      { type: 'heading', text: 'The Deeper Meaning of Mangal Dosha' },
      { type: 'paragraph', text: 'Rather than viewing Mangal Dosha as a curse, Vedic astrologers understand Mars as representing fiery, assertive, independent energy that simply needs the right partner and channel. A Manglik person often needs a partner who can match their passion, directness, and drive. The remedy is not fear, but wisdom — and the guidance of a skilled astrologer who can assess the full chart holistically.' },
    ],
  },
];

export const categories = ['All', 'Basics', 'Planets', 'Zodiac', 'Houses', 'Nakshatras', 'Remedies', 'Advanced', 'Compatibility', 'Transits'];

export const getBlogPost = (slug: string): BlogPost | undefined =>
  blogPosts.find(p => p.slug === slug);
